# Generated by Django 3.1.1 on 2021-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='latest_hash',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
